version: '3.8'

services:
  jupyterhub:
    build: .
    image: jupyter-hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - jupyterhub_data:/srv/jupyterhub/data
      - shared_data:/srv/data
    ports:
      - "8000:8000"
    networks:
      - jupyterhub

volumes:
  jupyterhub_data:
  shared_data:
  

networks:
  jupyterhub:
    name: jupyterhub
